version: '2'
services:
    natchiyardemo5-app:
        image: natchiyardemo5
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://natchiyardemo5-mysql:3306/natchiyardemo5?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9020:9020
    natchiyardemo5-mysql:
        extends:
            file: mysql.yml
            service: natchiyardemo5-mysql
